#FROM ubuntu:18.04
FROM nvidia/cuda:10.1-runtime-ubuntu18.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
# ENV DEBIAN_FRONTEND=noninteractive

# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
# ENV NVIDIA_REQUIRE_CUDA "cuda==10.1"

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu60 \
        libunwind8 \
        netcat \
        cmake \
        libssl1.0.0

WORKDIR /azp


# if the pool stops accepting jobs, check that there is not a new agent to download
# https://dev.azure.com/c3srdev/_settings/agentpools
RUN curl -LsS https://vstsagentpackage.azureedge.net/agent/2.154.3/vsts-agent-linux-x64-2.154.3.tar.gz | tar -xz
COPY ./start.sh .

RUN chmod +x start.sh

CMD ["./start.sh"]
